# Generated by Django 6.0.3 on 2026-03-19 06:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('Chat', 'Chat'), ('WhatsApp', 'WhatsApp'), ('Voice', 'Voice')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('escalated', 'Escalated')], default='draft', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('report_pdf', models.FileField(blank=True, upload_to='reports/')),
                ('transcript_file', models.FileField(blank=True, upload_to='transcripts/')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('language', models.CharField(default='English', max_length=64)),
                ('last_call_remark', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['name', 'patient_id'],
            },
        ),
        migrations.CreateModel(
            name='CallMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('agent', 'Agent'), ('patient', 'Patient'), ('system', 'System')], max_length=16)),
                ('message', models.TextField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pharmacy.callsession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=128)),
                ('indication', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(blank=True, max_length=255)),
                ('refill_due', models.DateField(blank=True, null=True)),
                ('indication_read', models.BooleanField(default=False)),
                ('direction_read', models.BooleanField(default=False)),
                ('prescriber', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown'), ('green', 'Taking'), ('red', 'Not taking'), ('yellow', 'New medicine')], default='unknown', max_length=16)),
                ('extra_medicines', models.JSONField(blank=True, default=list)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pharmacy.patient')),
            ],
            options={
                'ordering': ['patient__name', 'drug_name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='callsession',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sessions', to='pharmacy.patient'),
        ),
    ]
