# Generated by Django 6.0.3 on 2026-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callsession',
            name='attention_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='callsession',
            name='conversation_state',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='callsession',
            name='external_call_sid',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='callsession',
            name='last_error',
            field=models.TextField(blank=True),
        ),
    ]
